### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by wbypotential** [qiuapeng921/DnfHelper-Python#1]
您好！大佬  我是一名运维开发工程师  希望能学习下python方面的一些游戏脚本  能否学习下或者跟您一起编写这个工程！  感谢！

**Comment by code-gopher** [comment]
> 您好！大佬 我是一名运维开发工程师 希望能学习下python方面的一些游戏脚本 能否学习下或者跟您一起编写这个工程！ 感谢！

可以呀

**Comment by code-gopher** [comment]
> 您好！大佬 我是一名运维开发工程师 希望能学习下python方面的一些游戏脚本 能否学习下或者跟您一起编写这个工程！ 感谢！

其实我也是才学python

**Comment by wbypotential** [comment]
> > 您好！大佬 我是一名运维开发工程师 希望能学习下python方面的一些游戏脚本 能否学习下或者跟您一起编写这个工程！ 感谢！
> 
> 可以呀

我加了你QQ,但是你的要填你的真实姓名   我不知道加  要不加下我的！   1092506464
