### ISSUE TITLE
无读写权限是什么问题？

### ISSUE THREAD

**Issue by fankoyu2019** [qiuapeng921/DnfHelper-Python#12]
<class 'Exception'>
无读写权限
函数<module>,文件:F:\Repositories\DnfHelper-Python\main.py,行:52
函数main,文件:F:\Repositories\DnfHelper-Python\main.py,行:42

**Comment by code-gopher** [comment]
> <class 'Exception'> 无读写权限 函数,文件:F:\Repositories\DnfHelper-Python\main.py,行:52 函数main,文件:F:\Repositories\DnfHelper-Python\main.py,行:42

仔细看readme
