### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by final0920** [qiuapeng921/DnfHelper-Python#4]
老哥，我原本是做java开发的，有点python的基础。按照你的代码在更新基址后能够跑起来大部分功能，但是遇到了一些导致游戏闪退的问题。能否留个联系的方式，我想向你请教一下，可以有偿。

**Comment by qiuapeng921** [comment]
qq 1047871481

**Comment by code-gopher** [comment]
> 老哥，我原本是做java开发的，有点python的基础。按照你的代码在更新基址后能够跑起来大部分功能，但是遇到了一些导致游戏闪退的问题。能否留个联系的方式，我想向你请教一下，可以有偿。

qq 1047871481
